server:
  port: ${SERVER_PORT}

springdotenv:
  directory: ..

spring:
  application:
    name: service

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cors:
    allowed-origins: ${SPRING_CORS_ALLOWED_ORIGINS}

  web:
    base-url: ${SPRING_WEB_BASE_URL}

  keycloak:
    base-url: ${SPRING_KEYCLOAK_BASE_URL}
    internal-base-url: ${SPRING_KEYCLOAK_INTERNAL_BASE_URL:${SPRING_KEYCLOAK_BASE_URL}}
    realm: ${SPRING_KEYCLOAK_REALM}
    client-id: ${SPRING_KEYCLOAK_CLIENT_ID}
    redirect-url: ${SPRING_KEYCLOAK_REDIRECT_URL}
